config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :reservations, only: [:destroy, :edit, :update]

  get "/dashboard", to: "pages#dashboard"
  resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :reservations, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  validates :game, presence: true
  validates :description, presence: true
  validates :date, presence: true
  validates :capacity, presence: true
  validates :address, presence: true
  validates :fee, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :photo, PhotoUploader

  include PgSearch
  pg_search_scope :search_by_game,
    against: [:game],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
  end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :event
  belongs_to :user
  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations, dependent: :destroy
  has_many :events, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :avatar, PhotoUploader

  validates :nickname, uniqueness: true, presence: true
  validates :team, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :nickname, :team])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :nickname, :team, :birthday, :phone, :bio, :avatar])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @events = policy_scope(Event)
    if params[:game].present?
      @events = @events.search_by_game(params[:game])
      if params[:address].present?
        @events = @events.near(params[:address],20)
      end
    elsif params[:address].present?
      @events = @events.near(params[:address],20)
    end
    @markers = @events.map do |event|
      {
        lng: event.longitude,
        lat: event.latitude
      }
    end
  end

  def show
    @event = Event.find(params[:id])
    @reservation = Reservation.find_by(event_id: @event.id, user_id: current_user.id)
    authorize @event
    @available_seats = @event.capacity - @event.reservations.reduce(0) { |sum, res|
      sum + res.quantity
    }
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    authorize @event
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def edit
    @event = Event.find params[:id]
    authorize @event
    @event.save
  end

  def update
    @event = Event.find(params[:id])
    authorize @event
    @event.update(event_params)
    redirect_to event_path(@event)
  end


  def destroy
    @event = Event.find params[:id]
    authorize @event
    @event.destroy
    redirect_to dashboard_path
  end

  private

  def event_params
    params.require(:event).permit(:game, :date, :description, :address, :capacity, :fee, :photo, :photo_cache)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @events = Event.last(10)
  end

  def dashboard
    @reservations = current_user.reservations
    @events = current_user.events
    @events = policy_scope(Event)
  end

end

app/controllers/profils_controller.rb
class ProfilsController < ApplicationController


  def show

  end

  def dashboard
    @reservations = current_user.reservations
    @events = current_user.events
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def new
    @event = Event.find(params[:event_id])
    @reservation = Reservation.new
    @reservation.event = @event
    @reservation.user = current_user
    authorize @reservation
  end

  def create
    @reservation = Reservation.new(reservation_params)
    # we need `event_id` to asssociate reservation with corresponding event
    @event = Event.find(params[:event_id])
    @reservation.event = @event
    @reservation.user = current_user
    authorize @reservation
    @available_seats = @event.capacity - @event.reservations.reduce(0) { |sum, res|
      sum + res.quantity
    }
    if @reservation.save
      flash[:alert] = nil
      flash[:notice] = "Merci de votre réservation"
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
    @reservation.user = current_user
    authorize @reservation
  end

  def update
    @reservation = Reservation.find(params[:id])
    @event = @reservation.event
    @reservation.user = current_user
    authorize @reservation
    @quantity = reservation_params[:quantity]
    @available_seats = @event.capacity - @event.reservations.reduce(0) { |sum|
        sum + @quantity.to_i }
    if @reservation.update(reservation_params)
    flash[:alert] = nil
    flash[:notice] = "Votre réservation a été éditée"
    redirect_to event_path(@event)
    else
      render :edit
    end
  end


  def destroy
    @reservation = Reservation.find params[:id]
    authorize @reservation
    @reservation.delete
    redirect_to dashboard_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>

  <%= f.input :game %>
  <%= f.input :description %>
  <%= f.input :date,
              html5: true %>
  <%= f.input :address %>
  <%= f.input :capacity %>
  <%= f.input :fee %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>

  <div class="form-actions text-center">
    <div class="form-actions">
  <%= f.button :submit, "Add your event", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="container">
<h1>Mettre à jour votre match</h1>


<%= render 'form', event: @event %>
</div>

app/views/events/index.html.erb
<div class="box-map">

<div class="box-games">

<%= render 'shared/list_match', event: @event %>
</div>

<div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

</div>

app/views/events/new.html.erb
<div class="container">

<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
  <h1>Accueillir un match</h1>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
  <%= render 'form', event: @event %>
  </div>
</div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <h2><%=@event.game%> </h2>
      <p><%=@event.address%></p>
      <p>Le <%=@event.date%> </p>

      <div style="margin:10px 0;"><%= cl_image_tag(@event.photo,
      width: 700, height: 300, crop: :fill) %></div>

      <p><%=@event.description%> </p>
      <p>Il reste <%= @available_seats %> places dispos</p>
      <p>Prix : <%=@event.fee%> </p>
    </div>
  <div class="col-xs-12 col-sm-4">
    <p style="margin: 10px 0;">Organisé par :</p>
  <div class="box-panini" style="background-image:url(<% if @event.user.avatar? %><%= cl_image_path(@event.user.avatar, width: 400, height: 300, crop: :fill, gravity: :face) %>)<% end %>;">

    <span class="club"><%= @event.user.team %></span>

<div class="info">
    <h2><%= @event.user.nickname %></h2>
    <p><%= @event.user.bio %></p>
    </div>
  </div>
  <% if current_user != @event.user && @reservation == nil %>
    <%= link_to "Réserver", new_event_reservation_path(@event), :class => "btn btn-default" %>
   <% end %>
  <% if current_user != @event.user && @reservation != nil%>
  <%= link_to "Voir mes évènements et réservations", dashboard_path %>
  <% end %>
  <% if policy(@event).update? %>
    <%= link_to "Editer", edit_event_path(@event), :class => "btn btn-default" %>
  <% end %>
  <% if policy(@event).destroy? %>
    <%= link_to "Supprimer", event_path(@event),
      method: :delete,
      data: { confirm: "Vous êtes sûr?" },
      :class => "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Canap Plus</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="box">
    <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="row">
<div class="container">
<div class="col-xs-12 col-sm-6">
<h2>A l'extérieur</h2>
<ul>
  <%@reservations.each do |reservation|%>
    <li>
     <%= link_to "#{reservation.event.game}- #{reservation.event.date} - #{reservation.event.description}", event_path(reservation.event)%>
       <% if policy(reservation).destroy? %>
      <%= link_to "[Supprimer]", reservation_path(reservation),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
      <% end %>
        <% if policy(reservation).update? %>
       <%= link_to "[Éditer]", edit_reservation_path(reservation)%>
      <% end %>
    </li>
    <%end%>
</ul>
</div>


<div class="col-xs-12 col-sm-6">
<h2>A domicile</h2>

<ul>
  <%current_user.events.each do |event|%>
    <li>
      <%= link_to "#{event.game} - #{event.date} - #{event.description}", event_path(event)%>
    </li>
    <%end%>
</ul>
</div>


</div>
</div>

app/views/pages/home.html.erb
<div class="box-home">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="search">
        <p><strong>Cherchez un canapé prêt de chez vous</strong></p>
        <%= form_tag events_path, method: :get do %>
        <div class="form-group">
          <%= text_field_tag :game,
          params[:game],
          class: "form-control",
          placeholder: "Votre équipe"
          %>
        </div>
        <div class="form-group">
          <%= text_field_tag :address,
          params[:address],
          class: "form-control",
          placeholder: "Votre ville"
          %>
        </div>
        <%= submit_tag "Go", class: "form-control" %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <!--     <h2>Trouvez un <i class="fas fa-couch"></i> près de votre <i class="fas fa-home"></i></h2>
      -->
      <div class="description">
      <h1>Les matchs de votre équipe préférée entre amis</h1>
      </div>
    </div>
  </div>
</div>

<div class="games">
  <h2>Les prochains rendez-vous</h2>
  <%= render 'shared/list_match', event: @event %>
  </div>

app/views/profils/dashboard.html.erb
<div class="container">
<h1>Historique</h1>

<div class="row">
  <div class="col-xs-12 col-sm-6">
    <h2>Mes évènements</h2>
    <ul>
      <% @events.each do |event| %>
      <li><%= link_to event.game, event_path(event.id) %></li>
      <% end %>
    </ul>

  </div>
  <div class="col-xs-12 col-sm-6">
<h2>Mes réservations</h2>
<ul>
  <% @reservations.each do |reservation| %>
    <li><%= link_to reservation.event.game, event_path(reservation.event.id) %> (<%= reservation.event.user.nickname%>)</li>
  <% end %>

</ul>

  </div>
</div>
</div>

app/views/profils/show.html.erb
<div class="container">
<div class="row">
  <div class="col-xs-6 col-sm-8">
<h1><%= current_user.nickname %></h1>
<%= cl_image_tag(current_user.avatar,
      width: 300, height: 200, crop: :thumb) %>
<ul>
  <li><%= current_user.first_name %></li>
  <li><%= current_user.last_name %></li>
  <li><%= current_user.nickname %></li>
  <li><%= current_user.phone %></li>
  <li><%= current_user.team %></li>
  <li><%= current_user.bio %></li>
  <li><%= current_user.nickname %></li>
  <li><%= current_user.birthday %></li>
</ul>
</div>


<div class="col-xs-6 col-sm-4">
  <h2>Accès rapide</h2>
  <ul>
    <li><%= link_to "Historique", dashboard_path  %>
<li><%= link_to "Modifier mon profil", edit_user_registration_path  %></li>
<li><%= link_to "Modifier mon mot de passe", edit_user_password_path  %></li>
</ul>
</div>

</div>
</div>

app/views/reservations/edit.html.erb
<h1>Editer vos places réservées: <%= @reservation.quantity %> places </h1>
<%= simple_form_for(@reservation) do |f| %>

  <%= f.input :quantity, collection: 1..@reservation.event.capacity %>

  <%= f.button :submit, "Éditer" %>
<% end %>

app/views/reservations/new.html.erb
<h1>Réserver un événement</h1>
<%= simple_form_for([@event, @reservation]) do |f| %>

  <%= f.input :quantity, collection: 1..@event.capacity%>

  <%= f.button :submit, "Réserver" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_list_match.html.erb
<%@events.each do |event|%>

  <div class="game-list">
    <div class="game-avatar">
    <%= cl_image_tag(event.photo,
    width: 200, height: 100, crop: :thumb ) %>
    </div>
    <div class="game-info">
      <h4><%= link_to "#{event.game}", event_path(event) %> </h4
      <p><em> <%= event.date %> </em></p>
      <p><%= event.description %></p>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "canapplus.png", height: 50 %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

<%= link_to "Accueillir un match", new_event_path, :class => "navbar-wagon-item navbar-wagon-link"  %>

<%= link_to "Les prochains matchs", events_path, :class => "navbar-wagon-item navbar-wagon-link"  %>

<% if user_signed_in? %>


    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
      <% if current_user.avatar?%>
        <%= cl_image_tag(current_user.avatar,
        width: 35, height: 35, crop: :thumb, radius: :max, gravity: :face,:class => "avatar dropdown-toggle", :id => "navbar-wagon-menu", 'data-toggle' => "dropdown"  ) %>
      <% else %>
        <%= image_tag("avatar-placeholder.png", :class => "avatar dropdown-toggle", :id => "navbar-wagon-menu", 'data-toggle' => "dropdown") %>
      <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">


          <li><%= link_to "Mon profil", edit_user_registration_path  %></li>
          <li><%= link_to "Mes évènements et réservations",  dashboard_path %></li>
          <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
      <% elsif %>

<%= link_to "Connection", user_session_path, :class => "navbar-wagon-item navbar-wagon-link"  %>

<%= link_to "S'inscrire", new_user_registration_path, :class => "navbar-wagon-item navbar-wagon-link"  %>
<% end %>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

<li><%= link_to "Connection", new_event_path %></li>

<li><%= link_to "Inscription", events_path %></li>


      </ul>
    </div>


  </div>
</div>